### ISSUE TITLE
Remove $$dbClassInfo from builds

### ISSUE THREAD

**Issue by pcdummy** [qooxdoo/qxcompiler#10]
It would be nice if you could remove these lines from the output or give an option to disable it.

``` javascript

(function () {
  var $$dbClassInfo = {
    'unresolved': [{
      'name': 'qxc.tweets',
      'locations': [{
        'start': {
          'line': 45,
          'column': 24
        },
        'end': {
```

**Comment by johnspackman** [comment]
this is necessary for deferred dependencies, although it can be trimmed down quite a bit.  ive left it in for now but will modify it and move it to the end of the class file
