### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by pcdummy** [qooxdoo/qxcompiler#6]
Hi,

can you please make a npm package of this great compiler?

Thanks,
René

**Comment by pcdummy** [comment]
To explain this Request: I need that for [grunt-qxcompiler](https://www.npmjs.com/package/grunt-qxcompiler) where i currently include qxcompiler as submodule.

**Comment by johnspackman** [comment]
The plan is to integrate qxcompiler into qx proper, so can we do this so that the qooxdoo npm package is updated to include the compiler and have it work as a library as well as a module?

**Comment by pcdummy** [comment]
I would use a own npm package for qxcompiler and depend on it in qooxdoo.

**Comment by adrelino** [comment]
See https://github.com/qooxdoo/qooxdoo/issues/9137

**Comment by johnspackman** [comment]
done (qx-compiler npm package)
